services:
  - type: web
    name: shopify-descriptions-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production node server/index.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0