services:
  - type: web
    name: descricoes-shopify-api
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
        sync: false
      - key: SUPABASE_ANON_KEY
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: NODE_VERSION
        value: 18.0.0
      - key: PORT
        value: 10000